<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Reproducible Research: Peer Assessment 1</title>

<script src="PA1_template_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="PA1_template_files/highlight/default.css"
      type="text/css" />
<script src="PA1_template_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="PA1_template_files/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reproducible Research: Peer Assessment 1</h1>

</div>


<div id="loading-and-preprocessing-the-data" class="section level2">
<h2>Loading and preprocessing the data</h2>
<p>Show any code that is needed to:</p>
<ol style="list-style-type: decimal">
<li>Load the data (i.e. read.csv())<br />
</li>
<li>Process/transform the data (if necessary) into a format suitable for your analysis</li>
</ol>
<pre class="r"><code>library(dplyr)
library(lubridate)
library(stringr)
library(ggplot2)

### 1 ###
# read the data
data &lt;- read.csv(unz(&#39;activity.zip&#39;, &#39;activity.csv&#39;))

### 2 ###
# convert the date to a date format
data$date &lt;- ymd(data$date)

# modify the interval column to represent &quot;number of minutes elapsed so far today&quot;
# this is required to correct the scale since the least significant digits range 0-59 instead of 0-99
# a time variable is added to help with interpretability (I couldn&#39;t figure out a good way to use it directly)
data$interval &lt;- str_pad(data$interval, 4, pad = &quot;0&quot;)
data$time &lt;- paste0(substr(data$interval, 1, 2), &#39;:&#39;, substr(data$interval, 3, 4))
data$interval &lt;- as.numeric(substr(data$interval, 1, 2)) * 60 + as.numeric(substr(data$interval, 3, 4))</code></pre>
</div>
<div id="what-is-mean-total-number-of-steps-taken-per-day" class="section level2">
<h2>What is mean total number of steps taken per day?</h2>
<p>For this part of the assignment, you can ignore the missing values in the dataset.</p>
<ol style="list-style-type: decimal">
<li>Calculate the total number of steps taken per day<br />
</li>
<li>If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day<br />
</li>
<li>Calculate and report the mean and median of the total number of steps taken per day</li>
</ol>
<pre class="r"><code>### 1 ###
StepsPerDay &lt;- data %&gt;%
    group_by(date) %&gt;%
    summarize(total_steps = sum(steps, na.rm = TRUE))

### 2 ###
hist(StepsPerDay$total_steps, main = &#39;Histogram of Total Steps per Day&#39;, xlab = &#39;Total Steps&#39;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-2-1.png" alt="" /><!-- --></p>
<pre class="r"><code>### 3 ###
summary(StepsPerDay$total_steps)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0    6778   10400    9354   12810   21190</code></pre>
<p>The mean total steps per day can be seen above as: <strong>9354</strong></p>
</div>
<div id="what-is-the-average-daily-activity-pattern" class="section level2">
<h2>What is the average daily activity pattern?</h2>
<ol style="list-style-type: decimal">
<li>Make a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)<br />
</li>
<li>Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?</li>
</ol>
<pre class="r"><code>### 1 ###
StepsPerTime &lt;- data %&gt;%
    group_by(interval, time) %&gt;%
    summarize(mean_steps = mean(steps, na.rm = TRUE))

ggplot(data = StepsPerTime, aes(x = interval, y = mean_steps)) +
    geom_line() +
    labs(title = &#39;Mean Number of Steps over a 5 Minute Period&#39;, x = &#39;Minutes into Day&#39;, y = &#39;Mean Number of Steps&#39;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-3-1.png" alt="" /><!-- --></p>
<pre class="r"><code>### 2 ###
subset(StepsPerTime, mean_steps == max(StepsPerTime$mean_steps, na.rm = TRUE))</code></pre>
<pre><code>## Source: local data frame [1 x 3]
## Groups: interval [1]
## 
##   interval  time mean_steps
##      (dbl) (chr)      (dbl)
## 1      515 08:35   206.1698</code></pre>
<p>It can be seen above that there is a peak of activity in the morning, with highest activity found at <strong>08:35</strong> (24 hour time format).</p>
</div>
<div id="imputing-missing-values" class="section level2">
<h2>Imputing missing values</h2>
<p>Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.</p>
<ol style="list-style-type: decimal">
<li>Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)<br />
</li>
<li>Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.<br />
</li>
<li>Create a new dataset that is equal to the original dataset but with the missing data filled in.<br />
</li>
<li>Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?</li>
</ol>
<pre class="r"><code>### 1 ###
sum(is.na(data$steps))</code></pre>
<pre><code>## [1] 2304</code></pre>
<pre class="r"><code>mean(is.na(data$steps))</code></pre>
<pre><code>## [1] 0.1311475</code></pre>
<pre class="r"><code>### 2 ###
# my strategy for imputation is to replace a missing value with the average from that interval
# this average is already calculated previously in the StepsPerTime data frame
data_impute &lt;- data %&gt;%
    merge(StepsPerTime) %&gt;%
    mutate(steps = ifelse(is.na(steps), mean_steps, steps)) %&gt;%
    select(steps, date, interval, time)

### 3 ###
StepsPerDay_impute &lt;- data_impute %&gt;%
    group_by(date) %&gt;%
    summarize(total_steps = sum(steps, na.rm = TRUE))

### 4 ###
hist(StepsPerDay_impute$total_steps, main = &#39;Histogram of Total Steps per Day&#39;, xlab = &#39;Total Steps&#39;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-4-1.png" alt="" /><!-- --></p>
<pre class="r"><code>summary(StepsPerDay_impute$total_steps)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      41    9819   10770   10770   12810   21190</code></pre>
<p>The new histogram shows shifting of the data towards higher daily total step counts. This is to be expected since each day’s step count should be greater than or equal to the pre-imputation amount. Evidence of this increase can be seen with the new mean of <strong>10770</strong> and new median of <strong>10770</strong>, both of which are higher than the pre-imputation values.</p>
</div>
<div id="are-there-differences-in-activity-patterns-between-weekdays-and-weekends" class="section level2">
<h2>Are there differences in activity patterns between weekdays and weekends?</h2>
<p>For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.</p>
<ol style="list-style-type: decimal">
<li>Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.<br />
</li>
<li>Make a panel plot containing a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.</li>
</ol>
<pre class="r"><code>### 1 ###
weekdays &lt;- data_impute %&gt;%
    mutate(day = is.element(weekdays(date), c(&#39;Saturday&#39;, &#39;Sunday&#39;))) %&gt;%
    mutate(day = ifelse(day, &#39;weekend&#39;, &#39;weekday&#39;))  %&gt;%
    group_by(interval, time, day) %&gt;%
    summarize(mean_steps = mean(steps, na.rm = TRUE))

### 2 ###
ggplot(data = weekdays, aes(x = interval, y = mean_steps)) +
    facet_grid(day ~ .) +
    geom_line() + 
    labs(title = &#39;Mean Number of Steps over a 5 Minute Period&#39;, x = &#39;Minutes into Day&#39;, y = &#39;Mean Number of Steps&#39;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-5-1.png" alt="" /><!-- --></p>
<p>Several interesting patterns are evident at a glance. You can notice that activity is delayed on weekends, consistent with a possible explanation that the subject is sleeping in. While morning activity is lower on weekends, activity is displayed at a higher rate throughout the rest of the day, suggesting that the subject’s hobbies are more active than their regular weekday job. Finally, you can see activity is sustained longer on the weekends, indicating the subject is more likely to stay up late.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
